### ISSUE TITLE
hydro-devel: lwr_simulation doesn't have a package.xml

### ISSUE THREAD

**Issue by rhaschke** [RCPRG-ros-pkg/lwr_robot#3]
Did you forget to commit the package.xml for lwr_simulation?

**Comment by mjbogusz** [comment]
Check last commit (e.g. via `git log`) for the `lwr_simulation` directory - it was disabled on purpose. I'll ask the author for the reason.

PS. Sorry for necrobumping in case you get the notification.

**Comment by rhaschke** [comment]
There is a more obvious method to disable a package: using a `CATKIN_IGNORE` file. But thanks for this hint.

**Comment by mjbogusz** [comment]
@dseredyn FYI
